Repository nneaning/meaning_iOS, pull requests merged in 2021-01, with the labels that each got.

#9 [style] timestamp의 사진 촬영 view layout 잡기
  .github/PULL_REQUEST_TEMPLATE.md
  meaning/meaning.xcodeproj/project.pbxproj
  meaning/meaning/Global/Extension/Date+Extension.swift
  meaning/meaning/Global/Extension/String+Extension.swift
  meaning/meaning/Global/Extension/UIFont+Extension.swift
  meaning/meaning/Global/Extension/UILabel+Extension.swift
  meaning/meaning/Screen/Camera/Storyboard/Camera.storyboard
  meaning/meaning/Screen/Camera/ViewController/TimeStampVC.swift
  meaning/meaning/Screen/Mission/Storyboard/Mission.storyboard
  meaning/meaning/Screen/Mission/ViewController/DailyMaximVC.swift
  meaning/meaning/Support/Font/NanumSquareOTFBold.otf
  meaning/meaning/Support/Font/NanumSquareOTFExtraBold.otf
  meaning/meaning/Support/Font/NanumSquareOTFLight.otf
  meaning/meaning/Support/Font/NanumSquareOTFRegular.otf
  meaning/meaning/Support/Info.plist
Labels: Layout, p1, 🍎 iOS, 🐯 민희

#13 [feat] timestamp의 사진 촬영 feature 구현하기
  meaning/meaning/Screen/Camera/Storyboard/Camera.storyboard
  meaning/meaning/Screen/Camera/ViewController/TimeStampVC.swift
  meaning/meaning/Support/Info.plist
Labels: Feature, p1, 🍎 iOS, 🐯 민희

#18 [style] timestamp의 사진 확정 view layout 잡기
  meaning/meaning.xcodeproj/project.pbxproj
  meaning/meaning/Screen/Camera/Storyboard/Camera.storyboard
  meaning/meaning/Screen/Camera/ViewController/PhotoCheckVC.swift
Labels: Layout, p1, 🍎 iOS, 🐯 민희

#21 [feat] 촬영뷰 -> 확인뷰 데이터 넘기기 feature 구현
  meaning/meaning/Screen/Camera/Storyboard/Camera.storyboard
  meaning/meaning/Screen/Camera/ViewController/PhotoCheckVC.swift
  meaning/meaning/Screen/Camera/ViewController/TimeStampVC.swift
Labels: Feature, p1, 🍎 iOS, 🐯 민희

#29 [feat] 사진 확정 view 버튼 feature 구현하기
  meaning/Podfile.lock
  meaning/meaning/Screen/Camera/Storyboard/Camera.storyboard
  meaning/meaning/Screen/Camera/ViewController/PhotoCheckVC.swift
  meaning/meaning/Support/Info.plist
Labels: Feature, p1, 🍎 iOS, 🐯 민희

#30 [style] onboarding view의 닉네임 view layout 잡기
  meaning/meaning.xcodeproj/project.pbxproj
  meaning/meaning/Screen/Onboarding/Storyboard/Onboarding.storyboard
  meaning/meaning/Screen/Onboarding/ViewController/OnboardingNickVC.swift
  meaning/meaning/Support/Assets.xcassets/meaningBg1Img.imageset/Contents.json
  meaning/meaning/Support/Assets.xcassets/meaningBg1Img.imageset/meaningBg1Img.png
  meaning/meaning/Support/Assets.xcassets/meaningBg1Img.imageset/meaningBg1Img@2x.png
  meaning/meaning/Support/Assets.xcassets/meaningBg1Img.imageset/meaningBg1Img@3x.png
  meaning/meaning/Support/Info.plist
Labels: Layout, p1, 🍎 iOS, 🐯 민희

#32 [feat] onboarding view - 닉네임 view Textfield 기능 넣기
  meaning/meaning/Screen/Onboarding/ViewController/OnboardingNickVC.swift
  meaning/meaning/Support/Info.plist
Labels: Feature, p1, 🍎 iOS, 🐯 민희

#35 [feat] GroupListView 구현 #20
  meaning/meaning.xcodeproj/project.pbxproj
  meaning/meaning/Screen/GroupList/Storyboard/GroupList.storyboard
  meaning/meaning/Screen/GroupList/ViewController/Group.swift
  meaning/meaning/Screen/GroupList/ViewController/GroupCell.swift
  meaning/meaning/Screen/GroupList/ViewController/GroupListVC.swift
  meaning/meaning/Screen/GroupList/ViewController/GroupTable.swift
  meaning/meaning/Screen/GroupList/ViewController/GroupTableViewCell.swift
  meaning/meaning/Screen/TapBar/TabBarVC.swift
  meaning/meaning/Screen/TapBar/TestCameraVC.swift
  meaning/meaning/Screen/TapBar/TestGroupVC.swift
  meaning/meaning/Screen/TapBar/TestHomeVC.swift
  meaning/meaning/Support/Assets.xcassets/logoImg.imageset/Contents.json
  meaning/meaning/Support/Assets.xcassets/logoImg.imageset/logoImg.png
  meaning/meaning/Support/Assets.xcassets/logoImg.imageset/logoImg@2x.png
  meaning/meaning/Support/Assets.xcassets/logoImg.imageset/logoImg@3x.png
Labels: Epic, Feature, Layout, p2, 🐩 세은

#34 [feat] 회고 일기 뷰 등록하기 버튼 toast alert 추가
  meaning/meaning/Screen/Mission/Storyboard/Mission.storyboard
  meaning/meaning/Screen/Mission/ViewController/DailyDiaryVC.swift
Labels: Feature, p2, 🍎 iOS, 🦁 민승

#37 [style] onboarding view의 기상시간 view layout 잡기
  meaning/meaning.xcodeproj/project.pbxproj
  meaning/meaning/Screen/Onboarding/Storyboard/Onboarding.storyboard
  meaning/meaning/Screen/Onboarding/ViewController/OnboardingTimeVC.swift
  meaning/meaning/Support/Assets.xcassets/backBtn.imageset/Contents.json
  meaning/meaning/Support/Assets.xcassets/whiteBackBtn.imageset/Contents.json
  meaning/meaning/Support/Assets.xcassets/whiteBackBtn.imageset/whiteBackBtn.png
  meaning/meaning/Support/Assets.xcassets/whiteBackBtn.imageset/whiteBackBtn@2x.png
  meaning/meaning/Support/Assets.xcassets/whiteBackBtn.imageset/whiteBackBtn@3x.png
  meaning/meaning/Support/Info.plist
Labels: Layout, p1, 🍎 iOS, 🐯 민희

#45 [feat] onboarding view - 시간 view 시간 선택 기능 넣기
  meaning/meaning/Screen/Onboarding/ViewController/OnboardingTimeVC.swift
Labels: Feature, p1, 🍎 iOS, 🐯 민희

#49 [fix] DailyDiaryVC placeholder 문제 해결, 그 외 textView 관련 문제도 해결
  meaning/meaning.xcodeproj/project.pbxproj
  meaning/meaning/Screen/Mission/Storyboard/Mission.storyboard
  meaning/meaning/Screen/Mission/ViewController/DailyDiaryVC.swift
  meaning/meaning/Screen/Mission/ViewController/DailyMaximVC.swift
  meaning/meaning/Screen/Mission/ViewController/ShortReadingVC.swift
Labels: Feature, p2, 🍎 iOS, 🦁 민승

#53 [feat] GroupList 뷰에서 상세보기와 그룹 가입 결과 뷰 연결
  meaning/meaning.xcodeproj/project.pbxproj
  meaning/meaning/Screen/GroupList/Storyboard/GroupList.storyboard
  meaning/meaning/Screen/GroupList/ViewController/GroupCell.swift
  meaning/meaning/Screen/GroupList/ViewController/GroupDetailVC.swift
  meaning/meaning/Screen/GroupList/ViewController/GroupJoinVC.swift
  meaning/meaning/Screen/GroupList/ViewController/GroupListVC.swift
  meaning/meaning/Support/Assets.xcassets/closeBtn.imageset/Contents.json
  meaning/meaning/Support/Assets.xcassets/closeBtn.imageset/closeBtn.png
  meaning/meaning/Support/Assets.xcassets/closeBtn.imageset/closeBtn@2x.png
  meaning/meaning/Support/Assets.xcassets/closeBtn.imageset/closeBtn@3x.png
Labels: Layout, p2, 🍎 iOS, 🐩 세은

#52 [style] 기상 인증 뷰 layout 완료
  meaning/meaning.xcodeproj/project.pbxproj
  meaning/meaning/Screen/Mission/Storyboard/Mission.storyboard
  meaning/meaning/Screen/Mission/ViewController/PictureUploadVC.swift
  meaning/meaning/Support/Assets.xcassets/test_img.imageset/Contents.json
  meaning/meaning/Support/Assets.xcassets/test_img.imageset/test_img.png
Labels: Layout, help wanted, p2, 🍎 iOS, 🦁 민승

#59 [feat] Home 뷰 CollectionView 애니메이션
  meaning/meaning.xcodeproj/project.pbxproj
  meaning/meaning/Screen/Home/Cell/AnimationFlowLayout.swift
  meaning/meaning/Screen/Home/Cell/MissionCardCell.swift
  meaning/meaning/Screen/Home/Storyboard/Home.storyboard
  meaning/meaning/Screen/Home/ViewController/HomeVC.swift
Labels: Feature, p2, 🍎 iOS, 🐯 민희

#60 [feat] 그룹 정보 뷰 구현
  meaning/meaning.xcodeproj/project.pbxproj
  meaning/meaning/Screen/GroupFeed/Storyboard/GroupFeed.storyboard
  meaning/meaning/Screen/GroupFeed/ViewController/GroupInfoVC.swift
  meaning/meaning/Screen/GroupFeed/ViewController/MemberInfo.swift
  meaning/meaning/Screen/GroupFeed/ViewController/MemberTableViewCell.swift
  meaning/meaning/Support/Assets.xcassets/groupBackBtn.imageset/Contents.json
Labels: Feature, Layout, p3, 🍎 iOS, 🐩 세은

#63 [style] 마이 피드 뷰 레이아웃 rough ver.
  meaning/meaning.xcodeproj/project.pbxproj
  meaning/meaning/Global/Extension/WakeUpTimeView+Extension.swift
  meaning/meaning/Screen/MyPage/Storyboard/MyPage.storyboard
  meaning/meaning/Screen/MyPage/ViewController/FeedImage.swift
  meaning/meaning/Screen/MyPage/ViewController/MyPageFeedVC.swift
  meaning/meaning/Screen/MyPage/cell/FeedCollectionViewCell.swift
  meaning/meaning/Screen/MyPage/cell/FeedCollectionViewCell.xib
Labels: Layout, p2, question, 🍎 iOS, 🦁 민승

#69 [refac] cell 에서 WakeUpTimeView Extension이 활용 불가능한 부분을 수정함.
  meaning/meaning.xcodeproj/project.pbxproj
  meaning/meaning/Global/Extension/Toast+Extension.swift
  meaning/meaning/Global/Extension/UIViewController+Extension.swift
  meaning/meaning/Global/Extension/WakeUpTimeView+Extension.swift
  meaning/meaning/Screen/MyPage/ViewController/MyPageFeedVC.swift
Labels: 🍎 iOS, 🦁 민승

#68 [style] 마이피드/그룹 글 상세보기 view layout 잡기
  meaning/meaning.xcodeproj/project.pbxproj
  meaning/meaning/Global/Extension/WakeUpTimeView+Extension.swift
  meaning/meaning/Screen/GroupFeed/Cell/FeedDetailCell.swift
  meaning/meaning/Screen/GroupFeed/Storyboard/GroupFeed.storyboard
  meaning/meaning/Screen/GroupFeed/ViewController/FeedDetail.swift
  meaning/meaning/Screen/GroupFeed/ViewController/FeedDetailVC.swift
  meaning/meaning/Support/Assets.xcassets/IMG_0668.imageset/Contents.json
  meaning/meaning/Support/Assets.xcassets/IMG_0668.imageset/IMG_0668.JPG
Labels: Layout, p3, 🍎 iOS, 🐯 민희

#71 [style] 앱 아이콘 추가
  meaning/meaning.xcodeproj/project.pbxproj
  meaning/meaning/Support/Assets.xcassets/AppIcon.appiconset/Contents.json
  meaning/meaning/Support/Assets.xcassets/AppIcon.appiconset/icon-40.png
  meaning/meaning/Support/Assets.xcassets/AppIcon.appiconset/icon-40@2x.png
  meaning/meaning/Support/Assets.xcassets/AppIcon.appiconset/icon-40@3x.png
  meaning/meaning/Support/Assets.xcassets/AppIcon.appiconset/icon-60@2x.png
  meaning/meaning/Support/Assets.xcassets/AppIcon.appiconset/icon-60@3x.png
  meaning/meaning/Support/Assets.xcassets/AppIcon.appiconset/icon-72.png
  meaning/meaning/Support/Assets.xcassets/AppIcon.appiconset/icon-72@2x.png
  meaning/meaning/Support/Assets.xcassets/AppIcon.appiconset/icon-76.png
  meaning/meaning/Support/Assets.xcassets/AppIcon.appiconset/icon-76@2x.png
  meaning/meaning/Support/Assets.xcassets/AppIcon.appiconset/icon-83.5@2x.png
  meaning/meaning/Support/Assets.xcassets/AppIcon.appiconset/icon-small-50.png
  meaning/meaning/Support/Assets.xcassets/AppIcon.appiconset/icon-small-50@2x.png
  meaning/meaning/Support/Assets.xcassets/AppIcon.appiconset/icon-small.png
  meaning/meaning/Support/Assets.xcassets/AppIcon.appiconset/icon-small@2x.png
  meaning/meaning/Support/Assets.xcassets/AppIcon.appiconset/icon-small@3x.png
  meaning/meaning/Support/Assets.xcassets/AppIcon.appiconset/icon.png
  meaning/meaning/Support/Assets.xcassets/AppIcon.appiconset/icon@2x.png
  meaning/meaning/Support/Assets.xcassets/AppIcon.appiconset/ios-marketing.png
  meaning/meaning/Support/Assets.xcassets/AppIcon.appiconset/notification-icon@2x.png
  meaning/meaning/Support/Assets.xcassets/AppIcon.appiconset/notification-icon@3x.png
  meaning/meaning/Support/Assets.xcassets/AppIcon.appiconset/notification-icon~ipad.png
  meaning/meaning/Support/Assets.xcassets/AppIcon.appiconset/notification-icon~ipad@2x.png
  meaning/meaning/Support/Assets.xcassets/Contents.json
Labels: Layout, 🍎 iOS, 🐯 민희

#74 [feat] 그룹 생성 뷰 구현
  meaning/meaning.xcodeproj/project.pbxproj
  meaning/meaning/Global/Extension/UITextField+Extension.swift
  meaning/meaning/Global/Extension/UIViewController+Extension.swift
  meaning/meaning/Screen/GroupFeed/Storyboard/GroupFeed.storyboard
  meaning/meaning/Screen/GroupList/Storyboard/GroupList.storyboard
  meaning/meaning/Screen/GroupList/ViewController/GroupCompleteVC.swift
  meaning/meaning/Screen/GroupList/ViewController/GroupCreateVC.swift
  meaning/meaning/Screen/GroupList/ViewController/GroupListVC.swift
  meaning/meaning/Support/Assets.xcassets/backgroundImg.imageset/Contents.json
  meaning/meaning/Support/Assets.xcassets/backgroundImg.imageset/backgroundImg.png
  meaning/meaning/Support/Assets.xcassets/backgroundImg.imageset/backgroundImg@2x.png
  meaning/meaning/Support/Assets.xcassets/backgroundImg.imageset/backgroundImg@3x.png
Labels: Feature, Layout, p2, 🍎 iOS, 🐩 세은

#76 [feat] 홈 View의 미션 카드 View 연결하기
  meaning/Podfile.lock
  meaning/meaning.xcodeproj/project.pbxproj
  meaning/meaning/Global/Model/UserData.xcdatamodeld/UserData.xcdatamodel/contents
  meaning/meaning/Screen/Home/Storyboard/Home.storyboard
  meaning/meaning/Screen/Home/ViewController/HomeVC.swift
  meaning/meaning/Screen/Mission/Storyboard/Mission.storyboard
  meaning/meaning/Screen/Mission/ViewController/DailyDiaryVC.swift
  meaning/meaning/Screen/Mission/ViewController/DailyMaximVC.swift
  meaning/meaning/Screen/Mission/ViewController/PictureUploadVC.swift
  meaning/meaning/Screen/Mission/ViewController/ShortReadingVC.swift
Labels: Feature, p2, 🍎 iOS, 🐯 민희

#78 [style] group feed 뷰 layout 잡기
  meaning/meaning.xcodeproj/project.pbxproj
  meaning/meaning/Screen/GroupFeed/Cell/GroupFeedCell.swift
  meaning/meaning/Screen/GroupFeed/Cell/GroupFeedReusableView.swift
  meaning/meaning/Screen/GroupFeed/Cell/MemberTableViewCell.swift
  meaning/meaning/Screen/GroupFeed/Storyboard/GroupFeed.storyboard
  meaning/meaning/Screen/GroupFeed/ViewController/GroupFeedVC.swift
  meaning/meaning/Support/Assets.xcassets/groupSettingIc.imageset/Contents.json
  meaning/meaning/Support/Assets.xcassets/groupSettingIc.imageset/groupSettingIc.png
  meaning/meaning/Support/Assets.xcassets/groupSettingIc.imageset/groupSettingIc@2x.png
  meaning/meaning/Support/Assets.xcassets/groupSettingIc.imageset/groupSettingIc@3x.png
Labels: Layout, p3, 🍎 iOS, 🐯 민희

#79 [feat] 탭바에 home과 group list 연결하기
  meaning/meaning.xcodeproj/project.pbxproj
  meaning/meaning/Screen/GroupList/Storyboard/GroupList.storyboard
  meaning/meaning/Screen/GroupList/ViewController/GroupListNavigationController.swift
  meaning/meaning/Screen/Home/Storyboard/Home.storyboard
  meaning/meaning/Screen/Home/ViewController/HomeNavigationController.swift
  meaning/meaning/Screen/TapBar/ViewController/TabBarVC.swift
Labels: Feature, p1, 🍎 iOS, 🐯 민희

#82 [feat] 홈탭->마이페이지, 그룹탭->그룹생성 연결
  meaning/meaning/Screen/GroupList/ViewController/GroupListVC.swift
  meaning/meaning/Screen/Home/Storyboard/Home.storyboard
  meaning/meaning/Screen/Home/ViewController/HomeVC.swift
  meaning/meaning/Screen/MyPage/Storyboard/MyPage.storyboard
  meaning/meaning/Screen/MyPage/ViewController/MyPageFeedVC.swift
Labels: Feature, p1, 🍎 iOS, 🐯 민희

#84 [feat] 탭 바 가운데 카메라 버튼 연결
  meaning/meaning.xcodeproj/project.pbxproj
  meaning/meaning/Screen/Camera/Storyboard/Camera.storyboard
  meaning/meaning/Screen/Camera/ViewController/CameraNavigationController.swift
  meaning/meaning/Screen/Camera/ViewController/PhotoCheckVC.swift
  meaning/meaning/Screen/Camera/ViewController/TimeStampVC.swift
  meaning/meaning/Screen/Home/ViewController/HomeVC.swift
  meaning/meaning/Screen/Mission/ViewController/PictureUploadVC.swift
  meaning/meaning/Screen/TapBar/ViewController/TabBarVC.swift
Labels: Feature, p1, 🍎 iOS, 🐯 민희

#86 [feat] 마이피드 -> 글 상세보기, 그룹피드 -> 글 상세보기 연결하기
  meaning/meaning/Screen/GroupFeed/Cell/FeedDetailCell.swift
  meaning/meaning/Screen/GroupFeed/Storyboard/GroupFeed.storyboard
  meaning/meaning/Screen/GroupFeed/ViewController/FeedDetailVC.swift
  meaning/meaning/Screen/GroupFeed/ViewController/GroupFeedVC.swift
  meaning/meaning/Screen/GroupList/Storyboard/GroupList.storyboard
  meaning/meaning/Screen/GroupList/ViewController/GroupListVC.swift
  meaning/meaning/Screen/MyPage/ViewController/MyPageFeedVC.swift
Labels: Feature, p1, 🍎 iOS, 🐯 민희

#88 [upload] 서버 통신 기본 문서 제작
  meaning/meaning.xcodeproj/project.pbxproj
  meaning/meaning/Global/Service/APIService.swift
  meaning/meaning/Global/Service/APITarget.swift
Labels: Network, p1, 🍎 iOS, 🐯 민희

#89 [fix] APITarget 파일 수정
  meaning/meaning/Global/Service/APITarget.swift
Labels: Network, 🍎 iOS, 🐯 민희

#91 [feat] 사진 저장 후 toast로 알림 띄우기
  meaning/meaning/Screen/Camera/ViewController/PhotoCheckVC.swift
Labels: Feature, p1, 🍎 iOS, 🐯 민희

#93 [style] 홈 멘트 간격과 날짜 버튼 수정
  meaning/meaning/Screen/Home/Cell/MissionCardCell.swift
  meaning/meaning/Screen/Home/Storyboard/Home.storyboard
  meaning/meaning/Screen/Home/ViewController/HomeVC.swift
Labels: Layout, p2, 🍎 iOS, 🐯 민희

#96 [style] calendar 뷰 러프하게 layout 잡기
  meaning/meaning.xcodeproj/project.pbxproj
  meaning/meaning/Screen/Home/Storyboard/Home.storyboard
  meaning/meaning/Screen/Home/ViewController/CalendarVC.swift
Labels: Layout, p2, 🍎 iOS, 🐯 민희

#99 [upload] api setting
  meaning/meaning/Global/Service/APITarget.swift
Labels: Network, 🍎 iOS, 🐯 민희

#101 [docs] 토큰 재발급 api 추가
  meaning/Podfile.lock
  meaning/meaning/Global/Service/APIService.swift
  meaning/meaning/Global/Service/APITarget.swift
Labels: Network, 🍎 iOS, 🐯 민희

#105 [fix] groupList 버튼 영역 수정
  meaning/meaning/Screen/GroupList/Storyboard/GroupList.storyboard
  meaning/meaning/Screen/GroupList/ViewController/GroupListVC.swift
Labels: p2, 🐩 세은

#108 [feat] 홈 <-> 캘린더 움직이기
  meaning/meaning/Screen/Home/Storyboard/Home.storyboard
  meaning/meaning/Screen/Home/ViewController/CalendarVC.swift
  meaning/meaning/Screen/Home/ViewController/HomeVC.swift
Labels: Feature, p2, 🍎 iOS, 🐯 민희

#113 1st/style/login
  meaning/Podfile
  meaning/Podfile.lock
  meaning/meaning.xcodeproj/project.pbxproj
  meaning/meaning/Global/Extension/UIColor+Extension.swift
  meaning/meaning/Screen/Login/Storyboard/Login.storyboard
  meaning/meaning/Screen/Login/ViewController/LoginVC.swift
  meaning/meaning/Screen/Splash/Storyboard/LaunchScreen.storyboard
  meaning/meaning/Screen/Splash/ViewController/LaunchScreenVC.swift
  meaning/meaning/Support/AppDelegate.swift
  meaning/meaning/Support/Assets.xcassets/splashlogoImg.imageset/Contents.json
  meaning/meaning/Support/Assets.xcassets/splashlogoImg.imageset/splashlogoImg.png
  meaning/meaning/Support/Assets.xcassets/splashlogoImg.imageset/splashlogoImg@2x.png
  meaning/meaning/Support/Assets.xcassets/splashlogoImg.imageset/splashlogoImg@3x.png
  meaning/meaning/Support/Base.lproj/LaunchScreen.storyboard
  meaning/meaning/Support/Lottie/Launch.json
  meaning/meaning/Support/Lottie/LoginBackground.json
  meaning/meaning/Support/Lottie/SplashBackground.json
  meaning/meaning/Support/SceneDelegate.swift
Labels: Layout, p1, 🍎 iOS, 🦁 민승

#114 [style] home 뷰에서 미션완료시 멘트 수정하기
  meaning/Podfile.lock
  meaning/meaning/Screen/Home/Cell/MissionCardCell.swift
  meaning/meaning/Screen/Home/Storyboard/Home.storyboard
  meaning/meaning/Screen/Home/ViewController/HomeVC.swift
  meaning/meaning/Support/Assets.xcassets/cardCheckIc.imageset/Contents.json
  meaning/meaning/Support/Assets.xcassets/cardCheckIc.imageset/cardCheckIc.png
  meaning/meaning/Support/Assets.xcassets/cardCheckIc.imageset/cardCheckIc@2x.png
  meaning/meaning/Support/Assets.xcassets/cardCheckIc.imageset/cardCheckIc@3x.png
Labels: Layout, p2, 🍎 iOS, 🐯 민희

#116 [docs] api 추가
  meaning/meaning/Global/Service/APITarget.swift
Labels: Network, 🍎 iOS, 🐯 민희

#118 [feat] 순서에 맞지 않는 미션 클릭 시 toast 띄우기
  meaning/meaning/Screen/Home/ViewController/HomeVC.swift
Labels: Feature, p2, 🍎 iOS, 🐯 민희

#119 [docs] 그룹 리스트 api 작성
  meaning/meaning/Global/Service/APITarget.swift
Labels: Network, 🍎 iOS, 🐯 민희

#122 [style] 온보딩 환영합니다 뷰 layout 잡기
  meaning/meaning.xcodeproj/project.pbxproj
  meaning/meaning/Screen/Onboarding/Storyboard/Onboarding.storyboard
  meaning/meaning/Screen/Onboarding/ViewController/OnboardingEndVC.swift
  meaning/meaning/Screen/Onboarding/ViewController/OnboardingTimeVC.swift
Labels: Layout, p1, 🍎 iOS, 🐯 민희

#123 [refac] 기상 인증 뷰 뷰디자인 수정에 따른 대응 처리
  meaning/meaning/Screen/Mission/Storyboard/Mission.storyboard
  meaning/meaning/Screen/Mission/ViewController/PictureUploadVC.swift
Labels: Feature, Layout, p2, 🍎 iOS, 🦁 민승

#128 [network] 온보딩 서버 연결하기
  meaning/meaning.xcodeproj/project.pbxproj
  meaning/meaning/Global/Model/SimpleData.swift
  meaning/meaning/Global/Service/APIService.swift
  meaning/meaning/Screen/Onboarding/Storyboard/Onboarding.storyboard
  meaning/meaning/Screen/Onboarding/ViewController/OnboardingEndVC.swift
  meaning/meaning/Screen/Onboarding/ViewController/OnboardingTimeVC.swift
Labels: Network, p1, 🍎 iOS, 🐯 민희

#130 [style] calendar 구현하기
  meaning/meaning.xcodeproj/project.pbxproj
  meaning/meaning/Screen/Home/Cell/CalendarCell.swift
  meaning/meaning/Screen/Home/Storyboard/Home.storyboard
  meaning/meaning/Screen/Home/ViewController/CalendarData.swift
  meaning/meaning/Screen/Home/ViewController/CalendarVC.swift
  meaning/meaning/Support/Assets.xcassets/calendarBackImg.imageset/Contents.json
  meaning/meaning/Support/Assets.xcassets/calendarBackImg.imageset/calendarBackImg.png
  meaning/meaning/Support/Assets.xcassets/calendarBackImg.imageset/calendarBackImg@2x.png
  meaning/meaning/Support/Assets.xcassets/calendarBackImg.imageset/calendarBackImg@3x.png
  meaning/meaning/Support/Assets.xcassets/moonExample.imageset/Contents.json
  meaning/meaning/Support/Assets.xcassets/moonExample.imageset/moonExample.png
  meaning/meaning/Support/Assets.xcassets/moonExample.imageset/moonExample@2x.png
  meaning/meaning/Support/Assets.xcassets/moonExample.imageset/moonExample@3x.png
  meaning/meaning/Support/Assets.xcassets/starBlack.imageset/Contents.json
  meaning/meaning/Support/Assets.xcassets/starBlack.imageset/starBlack.png
  meaning/meaning/Support/Assets.xcassets/starBlack.imageset/starBlack@2x.png
  meaning/meaning/Support/Assets.xcassets/starBlack.imageset/starBlack@3x.png
  meaning/meaning/Support/Assets.xcassets/starWhite.imageset/Contents.json
  meaning/meaning/Support/Assets.xcassets/starWhite.imageset/starWhite.png
  meaning/meaning/Support/Assets.xcassets/starWhite.imageset/starWhite@2x.png
  meaning/meaning/Support/Assets.xcassets/starWhite.imageset/starWhite@3x.png
Labels: Layout, p2, 🍎 iOS, 🐯 민희

#139 [network] api 수정
  meaning/meaning/Global/Service/APITarget.swift
Labels: Network, 🍎 iOS, 🐯 민희

#134 [network] 로그인 서버 연결 success 에 대해서 완료
  meaning/Podfile.lock
  meaning/meaning.xcodeproj/project.pbxproj
  meaning/meaning/Global/Model/LoginData.swift
  meaning/meaning/Global/Service/APIService.swift
  meaning/meaning/Global/Service/APITarget.swift
  meaning/meaning/Global/Service/NetworkResult.swift
  meaning/meaning/Screen/Login/Storyboard/Login.storyboard
  meaning/meaning/Screen/Login/ViewController/LoginVC.swift
  meaning/meaning/Screen/Onboarding/Storyboard/Onboarding.storyboard
  meaning/meaning/Screen/Onboarding/ViewController/OnboardingNavigationController.swift
  meaning/meaning/Screen/Onboarding/ViewController/OnboardingNickVC.swift
  meaning/meaning/Screen/Onboarding/ViewController/OnboardingTimeVC.swift
  meaning/meaning/Screen/Splash/Storyboard/LaunchScreen.storyboard
  meaning/meaning/Screen/Splash/ViewController/LaunchScreenVC.swift
  meaning/meaning/Support/SceneDelegate.swift
Labels: Network, p1, 🍎 iOS, 🦁 민승

#144 [network] timestamp 서버 통신
  meaning/Podfile.lock
  meaning/meaning.xcodeproj/project.pbxproj
  meaning/meaning/Global/Model/TimestampData.swift
  meaning/meaning/Global/Service/APIService.swift
  meaning/meaning/Screen/Home/ViewController/HomeVC.swift
  meaning/meaning/Screen/Mission/Storyboard/Mission.storyboard
  meaning/meaning/Screen/Mission/ViewController/PictureUploadVC.swift
  meaning/meaning/Screen/Onboarding/ViewController/OnboardingTimeVC.swift
  meaning/meaning/Support/Info.plist
Labels: Network, p1, 🍎 iOS, 🐯 민희

#145 [network] 마이페이지 서버 연결
  meaning/meaning.xcodeproj/project.pbxproj
  meaning/meaning/Global/Extension/UIImageView+Extension.swift
  meaning/meaning/Global/Model/MypageData.swift
  meaning/meaning/Screen/MyPage/ViewController/MyPageFeedVC.swift
  meaning/meaning/Screen/MyPage/cell/FeedCollectionViewCell.swift
Labels: Feature, Network, p2, 🍎 iOS, 🐯 민희

#149 [network] splashServer 연결
  meaning/meaning.xcodeproj/project.pbxproj
  meaning/meaning/Global/Model/RefreshtokenData.swift
  meaning/meaning/Global/Service/APITarget.swift
  meaning/meaning/Screen/Login/ViewController/LoginVC.swift
  meaning/meaning/Screen/Onboarding/ViewController/OnboardingNickVC.swift
  meaning/meaning/Screen/Onboarding/ViewController/OnboardingTimeVC.swift
  meaning/meaning/Screen/Splash/ViewController/LaunchScreenVC.swift
  meaning/meaning/Support/SceneDelegate.swift
Labels: Network, p3, 🍎 iOS, 🦁 민승

#153 [network] 내 그룹 클릭 시 그룹 피드 서버 연결
  meaning/Podfile.lock
  meaning/meaning.xcodeproj/project.pbxproj
  meaning/meaning/Global/Model/GroupFeedData.swift
  meaning/meaning/Global/Service/APITarget.swift
  meaning/meaning/Screen/GroupFeed/Cell/GroupFeedCell.swift
  meaning/meaning/Screen/GroupFeed/Cell/GroupFeedReusableView.swift
  meaning/meaning/Screen/GroupFeed/ViewController/FeedDetailVC.swift
  meaning/meaning/Screen/GroupFeed/ViewController/GroupFeedVC.swift
  meaning/meaning/Screen/MyPage/ViewController/MyPageFeedVC.swift
  meaning/meaning/Support/Assets.xcassets/groupBlankIc.imageset/Contents.json
  meaning/meaning/Support/Assets.xcassets/groupBlankIc.imageset/groupBlankIc.png
  meaning/meaning/Support/Assets.xcassets/groupBlankIc.imageset/groupBlankIc@2x.png
  meaning/meaning/Support/Assets.xcassets/groupBlankIc.imageset/groupBlankIc@3x.png
Labels: Feature, Layout, Network, p2, 🍎 iOS, 🐯 민희

#156 [style] calendar 디자인 수정
  meaning/meaning/Screen/Home/Storyboard/Home.storyboard
  meaning/meaning/Screen/Home/ViewController/CalendarVC.swift
Labels: Layout, p2, 🍎 iOS, 🐯 민희

#160 [feat] 그룹 목록 (내그룹) -> 그룹 피드 전달할 값 넘기기
  meaning/meaning/Screen/GroupList/ViewController/GroupListVC.swift
Labels: Feature, p2, 🍎 iOS, 🐯 민희

#163 [refac] NetworkResult에서 필요 없는 case 삭제
  meaning/Podfile.lock
  meaning/meaning.xcodeproj/project.pbxproj
  meaning/meaning/Global/Service/APIService.swift
  meaning/meaning/Global/Service/NetworkResult.swift
  meaning/meaning/Screen/GroupFeed/ViewController/GroupFeedVC.swift
  meaning/meaning/Screen/GroupList/ViewController/GroupDetailVC.swift
  meaning/meaning/Screen/GroupList/ViewController/GroupListVC.swift
  meaning/meaning/Screen/Login/ViewController/LoginVC.swift
  meaning/meaning/Screen/Mission/ViewController/PictureUploadVC.swift
  meaning/meaning/Screen/MyPage/ViewController/MyPageFeedVC.swift
  meaning/meaning/Screen/Onboarding/ViewController/OnboardingTimeVC.swift
  meaning/meaning/Screen/Splash/ViewController/LaunchScreenVC.swift
Labels: Network, 🍎 iOS, 🦁 민승

#164 [network] 캘린더 서버 연결하기
  meaning/Podfile.lock
  meaning/meaning.xcodeproj/project.pbxproj
  meaning/meaning/Global/Model/CalendarData.swift
  meaning/meaning/Global/Service/APITarget.swift
  meaning/meaning/Screen/Home/Cell/CalendarCell.swift
  meaning/meaning/Screen/Home/Storyboard/Home.storyboard
  meaning/meaning/Screen/Home/ViewController/CalendarData.swift
  meaning/meaning/Screen/Home/ViewController/CalendarVC.swift
Labels: Network, p2, 🍎 iOS, 🐯 민희

#167 [network] 그룹 참가 신청 서버 통신
  meaning/Podfile.lock
  meaning/meaning.xcodeproj/project.pbxproj
  meaning/meaning/Global/Model/GroupCreateData.swift
  meaning/meaning/Global/Model/GroupListData.swift
  meaning/meaning/Screen/GroupList/Storyboard/GroupList.storyboard
  meaning/meaning/Screen/GroupList/ViewController/GroupCreateVC.swift
  meaning/meaning/Screen/GroupList/ViewController/GroupDetailVC.swift
  meaning/meaning/Screen/GroupList/ViewController/GroupJoinVC.swift
  meaning/meaning/Screen/GroupList/ViewController/GroupListVC.swift
Labels: Network, p2, 🍎 iOS, 🐩 세은

#172 [network] Mission-하루다짐 뷰 서버 연결 완료
  meaning/meaning.xcodeproj/project.pbxproj
  meaning/meaning.xcodeproj/xcshareddata/xcschemes/meaning.xcscheme
  meaning/meaning/Global/Model/DaypromiseData.swift
  meaning/meaning/Screen/Login/ViewController/LoginVC.swift
  meaning/meaning/Screen/Mission/Storyboard/Mission.storyboard
  meaning/meaning/Screen/Mission/ViewController/DailyMaximVC.swift
  meaning/meaning/Screen/Mission/ViewController/ShortReadingVC.swift
  meaning/meaning/Screen/Onboarding/ViewController/OnboardingTimeVC.swift
Labels: Network, p2, 🍎 iOS, 🦁 민승

#168 [network] Mission- 짧은독서 뷰에 bookreview API 연결
  meaning/meaning/Screen/Mission/Storyboard/Mission.storyboard
  meaning/meaning/Screen/Mission/ViewController/DailyMaximVC.swift
  meaning/meaning/Screen/Mission/ViewController/ShortReadingVC.swift
Labels: Network, p2, question, 🍎 iOS, 🦁 민승

#173 [network] 그룹 생성 서버 통신
  meaning/meaning/Global/Model/GroupCreateData.swift
  meaning/meaning/Screen/GroupList/Storyboard/GroupList.storyboard
  meaning/meaning/Screen/GroupList/ViewController/GroupCreateVC.swift
  meaning/meaning/Screen/GroupList/ViewController/GroupDetailVC.swift
  meaning/meaning/Screen/GroupList/ViewController/GroupJoinVC.swift
  meaning/meaning/Screen/GroupList/ViewController/GroupListVC.swift
  meaning/meaning/Screen/GroupList/ViewController/GroupTableViewCell.swift
  meaning/meaning/Screen/TapBar/ViewController/TabBarVC.swift
Labels: Network, p2, 🍎 iOS, 🐩 세은

#174 [feat][bug] 뷰 간 토큰 연결 및 오류 수정
  meaning/Podfile.lock
  meaning/meaning.xcodeproj/project.pbxproj
  meaning/meaning/Global/Model/LoginData.swift
  meaning/meaning/Screen/GroupFeed/ViewController/GroupFeedVC.swift
  meaning/meaning/Screen/GroupList/Storyboard/GroupList.storyboard
  meaning/meaning/Screen/GroupList/ViewController/GroupCreateVC.swift
  meaning/meaning/Screen/GroupList/ViewController/GroupDetailVC.swift
  meaning/meaning/Screen/GroupList/ViewController/GroupJoinVC.swift
  meaning/meaning/Screen/GroupList/ViewController/GroupListVC.swift
  meaning/meaning/Screen/Home/Cell/MissionCardCell.swift
  meaning/meaning/Screen/Home/ViewController/CalendarVC.swift
  meaning/meaning/Screen/Login/ViewController/LoginVC.swift
  meaning/meaning/Screen/Mission/Storyboard/Mission.storyboard
  meaning/meaning/Screen/Mission/ViewController/PictureUploadVC.swift
  meaning/meaning/Screen/Mission/ViewController/ShortReadingVC.swift
  meaning/meaning/Screen/MyPage/ViewController/MyPageFeedVC.swift
  meaning/meaning/Screen/Onboarding/ViewController/OnboardingTimeVC.swift
  meaning/meaning/Screen/Splash/ViewController/LaunchScreenVC.swift
  meaning/meaning/Support/Assets.xcassets/Contents.json
  meaning/meaning/Support/Assets.xcassets/IMG_0668.imageset/Contents.json
  meaning/meaning/Support/Assets.xcassets/IMG_0668.imageset/IMG_0668.JPG
  meaning/meaning/Support/SceneDelegate.swift
Labels: Feature, bug, 🍎 iOS, 🐯 민희

#176 [network] 그룹 사용자인지 알아보는 api 연결
  meaning/meaning.xcodeproj/project.pbxproj
  meaning/meaning/Global/Model/MyGroupData.swift
  meaning/meaning/Global/Model/TimestampData.swift
  meaning/meaning/Global/Service/APITarget.swift
  meaning/meaning/Screen/Mission/ViewController/PictureUploadVC.swift
Labels: Network, p1, 🍎 iOS, 🐯 민희

#178 [feat] feedDetail로 데이터 넘기기
  meaning/meaning/Global/Extension/Date+Extension.swift
  meaning/meaning/Screen/GroupFeed/Cell/FeedDetailCell.swift
  meaning/meaning/Screen/GroupFeed/ViewController/FeedDetailVC.swift
  meaning/meaning/Screen/GroupFeed/ViewController/GroupFeedVC.swift
  meaning/meaning/Screen/MyPage/ViewController/MyPageFeedVC.swift
Labels: Feature, p2, 🍎 iOS, 🐯 민희

#184 [network] Mission - 회고일기 뷰 서버 연결 완료
  meaning/Podfile.lock
  meaning/meaning.xcodeproj/project.pbxproj
  meaning/meaning/Global/Model/DailydiaryData.swift
  meaning/meaning/Screen/Login/ViewController/LoginVC.swift
  meaning/meaning/Screen/Mission/ViewController/DailyDiaryVC.swift
Labels: Layout, Network, p1, p2, 🍎 iOS, 🦁 민승

#185 [refac] 격언 나오는 뷰 색깔 수정, 다크모드 막음처리
  meaning/meaning/Screen/Mission/ViewController/DailyMaximVC.swift
  meaning/meaning/Support/SceneDelegate.swift
Labels: Layout, 🍎 iOS, 🦁 민승

#188 [style] mypage ment 수정
  meaning/Podfile.lock
  meaning/meaning.xcodeproj/project.pbxproj
  meaning/meaning/Screen/MyPage/ViewController/MyPageFeedVC.swift
Labels: Layout, p2, 🍎 iOS, 🐯 민희

#189 [network] 그룹 설정 서버 통신 및 그룹 생성 토스트 설정
  meaning/meaning.xcodeproj/project.pbxproj
  meaning/meaning/Global/Model/GroupInfoData.swift
  meaning/meaning/Global/Model/GroupListData.swift
  meaning/meaning/Screen/GroupFeed/Cell/MemberTableViewCell.swift
  meaning/meaning/Screen/GroupFeed/Storyboard/GroupFeed.storyboard
  meaning/meaning/Screen/GroupFeed/ViewController/GroupFeedVC.swift
  meaning/meaning/Screen/GroupFeed/ViewController/GroupInfoVC.swift
  meaning/meaning/Screen/GroupList/Storyboard/GroupList.storyboard
  meaning/meaning/Screen/GroupList/ViewController/GroupCreateVC.swift
  meaning/meaning/Screen/GroupList/ViewController/GroupDetailVC.swift
  meaning/meaning/Screen/GroupList/ViewController/GroupListVC.swift
Labels: Network, p3, 🍎 iOS, 🐩 세은

#190 [feat] 미션 완료 후 toast
  meaning/meaning/Global/Service/APITarget.swift
  meaning/meaning/Screen/Home/ViewController/HomeVC.swift
  meaning/meaning/Screen/Mission/ViewController/DailyDiaryVC.swift
  meaning/meaning/Screen/Mission/ViewController/DailyMaximVC.swift
  meaning/meaning/Screen/Mission/ViewController/PictureUploadVC.swift
  meaning/meaning/Screen/Mission/ViewController/ShortReadingVC.swift
Labels: Feature, p2, 🍎 iOS, 🐯 민희

#191 [fix] 서버 도메인 변경
  meaning/meaning/Global/Service/APITarget.swift
Labels: Network, 🍎 iOS

#193 [fix] 필요없는 파일 삭제 및 폴더링
  meaning/Podfile.lock
  meaning/meaning.xcodeproj/project.pbxproj
  meaning/meaning/Screen/GroupFeed/ViewController/FeedDetail.swift
  meaning/meaning/Screen/GroupFeed/ViewController/FeedDetailVC.swift
  meaning/meaning/Screen/GroupFeed/ViewController/GroupFeedVC.swift
  meaning/meaning/Screen/GroupFeed/ViewController/MemberInfo.swift
  meaning/meaning/Screen/GroupList/Cell/GroupCollectionCell.swift
  meaning/meaning/Screen/GroupList/Cell/GroupTableViewCell.swift
  meaning/meaning/Screen/Home/ViewController/AnimationFlowLayout.swift
  meaning/meaning/Screen/MyPage/ViewController/FeedImage.swift
  meaning/meaning/Screen/TapBar/Storyboard/TabBar.storyboard
  meaning/meaning/Screen/TapBar/ViewController/TestCameraVC.swift
  meaning/meaning/Screen/TapBar/ViewController/TestGroupVC.swift
  meaning/meaning/Screen/TapBar/ViewController/TestHomeVC.swift
  meaning/meaning/Support/Delegate/AppDelegate.swift
  meaning/meaning/Support/Delegate/Base.lproj/LaunchScreen.storyboard
  meaning/meaning/Support/Delegate/Base.lproj/Main.storyboard
  meaning/meaning/Support/Delegate/SceneDelegate.swift
  meaning/meaning/Support/Delegate/ViewController.swift
Labels: 🍎 iOS

#194 [feat] navigation swipe 추가
  meaning/meaning/Screen/Camera/ViewController/TimeStampVC.swift
  meaning/meaning/Screen/GroupList/ViewController/GroupListNavigationController.swift
  meaning/meaning/Screen/GroupList/ViewController/GroupListVC.swift
  meaning/meaning/Screen/Home/ViewController/HomeNavigationController.swift
  meaning/meaning/Screen/Home/ViewController/HomeVC.swift
  meaning/meaning/Screen/Onboarding/ViewController/OnboardingNavigationController.swift
  meaning/meaning/Screen/Onboarding/ViewController/OnboardingNickVC.swift
Labels: Feature, 🍎 iOS, 🐯 민희

#195 [fix] APIService 함수 모으기
  meaning/meaning/Global/Service/APIService.swift
  meaning/meaning/Screen/GroupFeed/ViewController/GroupFeedVC.swift
  meaning/meaning/Screen/GroupFeed/ViewController/GroupInfoVC.swift
  meaning/meaning/Screen/GroupList/ViewController/GroupCreateVC.swift
  meaning/meaning/Screen/GroupList/ViewController/GroupDetailVC.swift
  meaning/meaning/Screen/GroupList/ViewController/GroupJoinVC.swift
  meaning/meaning/Screen/GroupList/ViewController/GroupListVC.swift
  meaning/meaning/Screen/Home/ViewController/CalendarVC.swift
  meaning/meaning/Screen/Login/ViewController/LoginVC.swift
  meaning/meaning/Screen/Mission/ViewController/DailyDiaryVC.swift
  meaning/meaning/Screen/Mission/ViewController/DailyMaximVC.swift
  meaning/meaning/Screen/Mission/ViewController/PictureUploadVC.swift
  meaning/meaning/Screen/Mission/ViewController/ShortReadingVC.swift
  meaning/meaning/Screen/MyPage/ViewController/MyPageFeedVC.swift
  meaning/meaning/Screen/Onboarding/ViewController/OnboardingTimeVC.swift
  meaning/meaning/Screen/Splash/ViewController/LaunchScreenVC.swift
Labels: Network, 🍎 iOS, 🐯 민희

#197 [fix] label 문구 보이는 것 수정
  meaning/Podfile.lock
  meaning/meaning/Screen/GroupList/Storyboard/GroupList.storyboard
Labels: Layout, 🍎 iOS, 🐯 민희

#198 [refec] Extension 수정 및 통일
  meaning/meaning/Global/Extension/UIViewController+Extension.swift
  meaning/meaning/Screen/Camera/ViewController/PhotoCheckVC.swift
  meaning/meaning/Screen/GroupList/ViewController/GroupCreateVC.swift
  meaning/meaning/Screen/Home/ViewController/HomeVC.swift
  meaning/meaning/Screen/Login/ViewController/LoginVC.swift
  meaning/meaning/Screen/Mission/ViewController/DailyDiaryVC.swift
  meaning/meaning/Screen/Mission/ViewController/DailyMaximVC.swift
  meaning/meaning/Screen/Mission/ViewController/ShortReadingVC.swift
Labels: Feature, 🍎 iOS, 🐯 민희

#201 [refec] 그룹 조건 검사문 수정
  meaning/meaning/Global/Service/APITarget.swift
  meaning/meaning/Screen/GroupList/ViewController/GroupCreateVC.swift
Labels: Network, 🍎 iOS, 🐯 민희

#202 [refac] Mission뷰 디자인 변경에 따른 코드 수정
  meaning/Podfile.lock
  meaning/meaning.xcodeproj/project.pbxproj
  meaning/meaning/Screen/Home/ViewController/HomeNavigationController.swift
  meaning/meaning/Screen/Mission/Storyboard/Mission.storyboard
  meaning/meaning/Screen/Mission/ViewController/DailyMaximVC.swift
  meaning/meaning/Screen/Mission/ViewController/PictureUploadVC.swift
Labels: Layout, enhancement, p2, 🍎 iOS, 🦁 민승
